---
sudo: false

language: python
python:
  - "2.7"
  - "3.5"

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible

before_script:
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  - ansible --version
  - ansible-galaxy install likg.csf

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --become

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
