---
dist: trusty
sudo: false
language: python
services: docker
cache: pip
addons:
  apt:
    packages:
    - python-pip

env:
  global:
    - _ANSIBLE_CONNECTION=local
    - _ANSIBLE_PLAYBOOK=tests/docker_playbook.yml
  matrix:
    - _ANSIBLE_CONNECTION=ssh _ANSIBLE_PLAYBOOK=tests/test.yml
      _DOCKER_NAME=alpine _DOCKER_IMAGE=alpine
    - _DOCKER_NAME=centos6 _DOCKER_IMAGE=geerlingguy/docker-centos6-ansible
    - _DOCKER_NAME=centos7 _DOCKER_IMAGE=geerlingguy/docker-centos7-ansible
    - _DOCKER_NAME=debian8 _DOCKER_IMAGE=geerlingguy/docker-debian8-ansible
    - _DOCKER_NAME=debian9 _DOCKER_IMAGE=geerlingguy/docker-debian9-ansible
    - _DOCKER_NAME=ubuntu1604 _DOCKER_IMAGE=geerlingguy/docker-ubuntu1604-ansible
#    - _DOCKER_NAME=fedora27 _DOCKER_IMAGE=geerlingguy/docker-fedora27-ansible
# ansible module dnf : unsupported parameter for module: update_cache

matrix:
  fast_finish: true

before_install:
  - >
    ssh-keygen -t rsa -C travis@localhost -q -P '' -f ~/.ssh/id_rsa ;
    cat /home/travis/.ssh/id_rsa.pub >> /home/travis/.ssh/authorized_keys ;
    printf 'Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n' > /home/travis/.ssh/config;
  
install:
#  - pip install git+git://github.com/ansible/ansible.git@devel
  - travis_retry pip install --upgrade ansible ansible-lint
  - travis_retry docker pull ${_DOCKER_IMAGE}

before_script:
  - printf '[defaults]\nroles_path=../\nhost_key_checking = False\nretry_files_enabled = False\n\n[ssh_connection]\npipelining = True\n' > ansible.cfg
  - printf 'localhost' > inventory
  - sudo ln -s /bin/true /usr/sbin/sendmail
  - ansible --version

script:
  - ansible-lint -v ${_ANSIBLE_PLAYBOOK}
  - >
    ansible-playbook -i inventory ${_ANSIBLE_PLAYBOOK}
    --connection=${_ANSIBLE_CONNECTION}
    --extra-vars "DOCKER_NAME=${_DOCKER_NAME} DOCKER_IMAGE=${_DOCKER_IMAGE}"
    --skip-tags "destroy"
    -vv
  - >
    ANSIBLE_LOG_PATH=/tmp/idempotence.log
    ansible-playbook -i inventory ${_ANSIBLE_PLAYBOOK}
    --connection=${_ANSIBLE_CONNECTION}
    --extra-vars "DOCKER_NAME=${_DOCKER_NAME} DOCKER_IMAGE=${_DOCKER_IMAGE}"
  - >
    awk '/PLAY RECAP/,/EOF/
    {if (NF && $6 !~ "PLAY" && $9$10$11 !~ "changed=0unreachable=0failed=0" ) status=1 } END
    { print (status)? "Idempotence test: FAIL" : "Idempotence test: PASS"; exit status }'
    /tmp/idempotence.log

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
