---
language: python
python:
  - "2.7"
  - "3.5"

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible

before_script:
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  - ansible --version

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory -v
  - >
    ansible-playbook tests/test.yml -i tests/inventory
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
